name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}   # checkout the correct branch name
        fetch-depth: 0                # fetch the whole repo history
    
    - name: Git Version
      id: version
      uses: codacy/git-version@2.7.1
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: devopsifyme
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag devopsifyme/wslpipeproxy:${{ steps.version.outputs.version }}

    - name: Push Docker image
      if: github.event_name != 'pull_request'
      run: docker push devopsifyme/wslpipeproxy:${{ steps.version.outputs.version }}

    - name: Tag Docker Image as latest
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag devopsifyme/wslpipeproxy:${{ steps.version.outputs.version }} devopsifyme/wslpipeproxy:latest 
        docker push devopsifyme/wslpipeproxy:latest

    - name: Archive build output
      run: |
        docker create --name output devopsifyme/wslpipeproxy:${{ steps.version.outputs.version }}
        docker cp output:/install/ output/
        docker container rm output
        tar -czvf wslpipeproxy-${{ steps.version.outputs.version }}.tar.gz /output

    - name: Upload build output
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: output/

